version: '3.6'
services:
  caddy:
    image: caddy:2-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - $PWD/data/caddy/Caddyfile:/etc/caddy/Caddyfile
    networks:
      - web
      - internal
  customer-site-fe:
    image: rocketsgraphql/next-fe:latest
    env_file:
      - ./fe-envfile
    restart: always
    ports:
      - "9001:90"
    depends_on:
      - "customer-site-be"
    links:
      - "customer-site-be"
  customer-site-be:
    image: rocketsgraphql/customer-site-be:latest
    env_file:
      - ./be-envfile
    ports:
      - "5000:5000"
    restart: always
  customer-site-docs:
    image: rocketsgraphql/customer-site-docs:latest
    ports:
      - "3000:3000"
    restart: always
networks:
  web:
    external: true
  internal:
    external: false
    driver: bridge


