version: '3.6'
services:
  customer-site-fe:
    image: rocketsgraphql/next-fe:latest
    env_file:
      - ./fe-envfile
    restart: always
    ports:
      - 9001:9001
    depends_on:
      - "customer-site-be"
    links:
      - "customer-site-be"
  customer-site-be:
    image: rocketsgraphql/customer-site-be:latest
    env_file:
      - ./be-envfile
    ports:
      - "7777:7777"
    restart: always
  customer-site-docs:
    image: rocketsgraphql/customer-site-docs:latest
    ports:
      - "3000:3000"
    restart: always
networks:
  web:
    external: true
  internal:
    external: false
    driver: bridge


